// nolint: lll

// НЕ РЕДАКТИРОВАТЬ! Изменения будут перезаписаны при следующей генерации.
// Code generated by running "go generate" by utility db2struct: "https://github.com/webnice/d2s"; DO NOT EDIT.
// Generator: db2struct (go install github.com/webnice/d2s/db2struct@latest)

// Структура создана автоматически на основе структуры таблицы базы данных.
// Название таблицы: "goose_db_version"

// Package migration
package migration

import nul "gopkg.in/webnice/lin.v1/nl"

// DbVersion Лог миграций
type DbVersion struct {
	ID        uint64   `db:"id"         gorm:"column:id;primary_key;        AUTO_INCREMENT;NOT NULL;DEFAULT NULL;precision:20;type:BIGINT(20) UNSIGNED"` // Уникальный идентификатор записи.
	VersionID int64    `db:"version_id" gorm:"column:version_id;            NOT NULL;DEFAULT NULL;precision:19;type:BIGINT(20)"                        ` // Номер версии базы данных.
	IsApplied bool     `db:"is_applied" gorm:"column:is_applied;            NOT NULL;DEFAULT NULL;type:TINYINT(1)"                                     ` // Истина - миграция применена. Ложь - миграция не применена.
	Tstamp    nul.Time `db:"tstamp"     gorm:"column:tstamp;                NULL;DEFAULT 'current_timestamp()';type:TIMESTAMP"                         ` // Дата и время миграции.
}
